Repository Jonas-Grill/ready-to-ride, pull requests merged in 2022-05, with the labels that each got.

#1 Update README.md
  README.md
  documentation/LOGO.PNG
Labels: documentation

#2 Initialized front end
  frontend/.gitignore
  frontend/.idea/.gitignore
  frontend/.idea/.name
  frontend/.idea/compiler.xml
  frontend/.idea/gradle.xml
  frontend/.idea/misc.xml
  frontend/app/.gitignore
  frontend/app/build.gradle
  frontend/app/proguard-rules.pro
  frontend/app/src/androidTest/java/com/readytoride/ExampleInstrumentedTest.kt
  frontend/app/src/main/AndroidManifest.xml
  frontend/app/src/main/java/com/readytoride/ExampleActivity
  frontend/app/src/main/java/com/readytoride/MainActivity.kt
  frontend/app/src/main/java/com/readytoride/data/hierKommtDerAPIAnbidungskramRein
  frontend/app/src/main/java/com/readytoride/example2/Example2Activity
  frontend/app/src/main/java/com/readytoride/example2/Example2ViewModel
  frontend/app/src/main/java/com/readytoride/models/hierKommenDieDatenSchemasBzwModelleRein
  frontend/app/src/main/java/com/readytoride/wennEineActivityNurAusEinerFileBzwKlasseBestehtDirektHierReinWennNichtEinExtraPackageDafür
  frontend/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  frontend/app/src/main/res/drawable/ic_launcher_background.xml
  frontend/app/src/main/res/layout/activity_main.xml
  frontend/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  frontend/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  frontend/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  frontend/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  frontend/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  frontend/app/src/main/res/values-night/themes.xml
  frontend/app/src/main/res/values/colors.xml
  frontend/app/src/main/res/values/strings.xml
  frontend/app/src/main/res/values/themes.xml
  frontend/app/src/main/res/xml/backup_rules.xml
  frontend/app/src/main/res/xml/data_extraction_rules.xml
  frontend/app/src/test/java/com/readytoride/ExampleUnitTest.kt
  frontend/build.gradle
  frontend/gradle.properties
  frontend/gradle/wrapper/gradle-wrapper.jar
  frontend/gradle/wrapper/gradle-wrapper.properties
  frontend/gradlew
  frontend/gradlew.bat
  frontend/settings.gradle
Labels: good first issue

#4 Horses & Trainer Page
  frontend/.idea/misc.xml
  frontend/app/build.gradle
  frontend/app/src/main/java/com/readytoride/MainActivity.kt
  frontend/app/src/main/java/com/readytoride/ui/horse/Horse.kt
  frontend/app/src/main/java/com/readytoride/ui/horse/HorseDatasource.kt
  frontend/app/src/main/java/com/readytoride/ui/horse/HorseFragment.kt
  frontend/app/src/main/java/com/readytoride/ui/horse/HorseItemAdapter.kt
  frontend/app/src/main/java/com/readytoride/ui/horse/HorseViewModel.kt
  frontend/app/src/main/java/com/readytoride/ui/horsedetail/HorseDetail.kt
  frontend/app/src/main/java/com/readytoride/ui/horsedetail/HorseDetailViewModel.kt
  frontend/app/src/main/java/com/readytoride/ui/trainer/Trainer.kt
  frontend/app/src/main/java/com/readytoride/ui/trainer/TrainerDatasource.kt
  frontend/app/src/main/java/com/readytoride/ui/trainer/TrainerFragment.kt
  frontend/app/src/main/java/com/readytoride/ui/trainer/TrainerItemAdapter.kt
  frontend/app/src/main/java/com/readytoride/ui/trainerdetail/AchievementsItemAdapter.kt
  frontend/app/src/main/java/com/readytoride/ui/trainerdetail/TrainerDetail.kt
  frontend/app/src/main/java/com/readytoride/ui/trainerdetail/TrainerDetailViewModel.kt
  frontend/app/src/main/res/drawable/horse1.png
  frontend/app/src/main/res/drawable/horse10.png
  frontend/app/src/main/res/drawable/horse2.png
  frontend/app/src/main/res/drawable/horse3.png
  frontend/app/src/main/res/drawable/horse4.png
  frontend/app/src/main/res/drawable/horse5.png
  frontend/app/src/main/res/drawable/horse6.png
  frontend/app/src/main/res/drawable/horse7.png
  frontend/app/src/main/res/drawable/horse8.png
  frontend/app/src/main/res/drawable/horse9.png
  frontend/app/src/main/res/drawable/ic_baseline_cake_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_category_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_color_lens_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_description_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_fitness_center_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_height_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_person_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_school_24.xml
  frontend/app/src/main/res/drawable/ic_baseline_speed_24.xml
  frontend/app/src/main/res/drawable/ic_horse_human.xml
  frontend/app/src/main/res/drawable/trainer1.png
  frontend/app/src/main/res/drawable/trainer2.png
  frontend/app/src/main/res/drawable/trainer3.png
  frontend/app/src/main/res/drawable/trainer4.png
  frontend/app/src/main/res/drawable/trainer5.png
  frontend/app/src/main/res/layout/fragment_horse.xml
  frontend/app/src/main/res/layout/fragment_horse_detail.xml
  frontend/app/src/main/res/layout/fragment_trainer.xml
  frontend/app/src/main/res/layout/fragment_trainer_detail.xml
  frontend/app/src/main/res/layout/list_item_horse.xml
  frontend/app/src/main/res/layout/list_item_trainer.xml
  frontend/app/src/main/res/layout/list_item_trainer_achievements.xml
  frontend/app/src/main/res/navigation/mobile_navigation.xml
  frontend/app/src/main/res/values/strings.xml
  frontend/build.gradle
  frontend/settings.gradle
Labels: enhancement

#5 Finished Openapi specification
  .github/workflows/cd.yaml
  .gitignore
  .idea/.gitignore
  .idea/markdown.xml
  .idea/misc.xml
  ready-to-ride.json
Labels: enhancement

#6 Init backend
  .idea/misc.xml
  backend/.env
  backend/.env.example
  backend/.idea/.gitignore
  backend/.idea/deno.xml
  backend/.idea/misc.xml
  backend/.idea/modules.xml
  backend/README.md
  backend/config/config.ts
  backend/controllers/userController.ts
  backend/deps.ts
  backend/exceptions/httpException.ts
  backend/main.ts
  backend/middleware/errorHandlerMiddleware.ts
  backend/repositories/userRepo.ts
  backend/routes.ts
  backend/services/userService.ts
  backend/types/user.ts
Labels: enhancement

#7 Fixed openapi
  ready-to-ride.json
Labels: enhancement

#8 Added /users/me
  ready-to-ride.json
Labels: enhancement

#9 Added requests for the different enums
  ready-to-ride.json
Labels: enhancement

#10 Create CI workflow
  .github/workflows/ci.yaml
Labels: enhancement

#11 User impl
  backend/.env
  backend/.env.example
  backend/.idea/.gitignore
  backend/.idea/markdown.xml
  backend/.idea/workspace.xml
  backend/config/config.ts
  backend/config/db-connection.ts
  backend/controllers/userController.ts
  backend/deps.ts
  backend/exceptions/invalidDataException.ts
  backend/exceptions/invalidIdException.ts
  backend/middleware/authMiddleware.ts
  backend/middleware/errorHandlerMiddleware.ts
  backend/models/userModel.ts
  backend/repositories/userRepo.ts
  backend/routes.ts
  backend/services/userService.ts
  backend/types/focus.ts
  backend/types/proficiency.ts
  backend/types/user.ts
  backend/types/userRole.ts
  ready-to-ride.json
Labels: enhancement
